apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: agones-game-launcher
  name: agones-game-launcher
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: agones-game-launcher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: agones-game-launcher
    spec:
      containers:
      - image: game-launcher
        imagePullPolicy: IfNotPresent
        name: agones-game-launcher
        ports:
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: agones-game-launcher
spec:
  selector:
    app: agones-game-launcher
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
# status:
#   loadBalancer:
#     ingress:
#     - ip: 192.168.59.104
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: agones-localhost
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: #set-hostname
    http:
      paths:
      - backend:
          service:
            name: agones-game-launcher
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts: #set-hostname
    secretName: ssl-certificates
status:
  loadBalancer: {}